#!/usr/bin/env python3
"""
build-places.py — generate data/places.json, a small lookup table used by the
Find My Reps tool to map a user's typed input (city, county, ZIP-ish, state
name) to a (state, county, city) tuple.

Coverage:
  - All 50 states + DC + "National" (US)
  - All 50 state capitals
  - Top ~200 US cities by population (well-known, commonly typed)
  - All 67 Florida counties + most Florida cities (since FL is our deepest state)

The file ships to the browser and drives autocomplete on /find-my-reps.html.
Keep it compact: each entry is {name, state, county?, display, aliases}.

Output format:
{
  "cities": [ { "name": "Melbourne", "state": "FL", "county": "Brevard",
                "display": "Melbourne, Florida (Brevard County)",
                "aliases": ["melbourne fl", "melbourne florida"] }, ... ],
  "counties": [ { "name": "Brevard County", "state": "FL",
                  "display": "Brevard County, Florida",
                  "aliases": ["brevard", "brevard county"] }, ... ],
  "states": [ { "code": "FL", "name": "Florida",
                "display": "State of Florida",
                "aliases": ["fl", "florida", "state of florida"] }, ... ]
}
"""
import json
from pathlib import Path

BASE = Path(__file__).parent
OUT = BASE / 'data' / 'places.json'

STATES = {
    'AL': 'Alabama', 'AK': 'Alaska', 'AZ': 'Arizona', 'AR': 'Arkansas',
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut', 'DE': 'Delaware',
    'FL': 'Florida', 'GA': 'Georgia', 'HI': 'Hawaii', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'IA': 'Iowa', 'KS': 'Kansas',
    'KY': 'Kentucky', 'LA': 'Louisiana', 'ME': 'Maine', 'MD': 'Maryland',
    'MA': 'Massachusetts', 'MI': 'Michigan', 'MN': 'Minnesota', 'MS': 'Mississippi',
    'MO': 'Missouri', 'MT': 'Montana', 'NE': 'Nebraska', 'NV': 'Nevada',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico', 'NY': 'New York',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island', 'SC': 'South Carolina',
    'SD': 'South Dakota', 'TN': 'Tennessee', 'TX': 'Texas', 'UT': 'Utah',
    'VT': 'Vermont', 'VA': 'Virginia', 'WA': 'Washington', 'WV': 'West Virginia',
    'WI': 'Wisconsin', 'WY': 'Wyoming', 'DC': 'District of Columbia',
}

# State capitals (for everyone who types their state capital)
STATE_CAPITALS = {
    'AL': 'Montgomery', 'AK': 'Juneau', 'AZ': 'Phoenix', 'AR': 'Little Rock',
    'CA': 'Sacramento', 'CO': 'Denver', 'CT': 'Hartford', 'DE': 'Dover',
    'FL': 'Tallahassee', 'GA': 'Atlanta', 'HI': 'Honolulu', 'ID': 'Boise',
    'IL': 'Springfield', 'IN': 'Indianapolis', 'IA': 'Des Moines', 'KS': 'Topeka',
    'KY': 'Frankfort', 'LA': 'Baton Rouge', 'ME': 'Augusta', 'MD': 'Annapolis',
    'MA': 'Boston', 'MI': 'Lansing', 'MN': 'Saint Paul', 'MS': 'Jackson',
    'MO': 'Jefferson City', 'MT': 'Helena', 'NE': 'Lincoln', 'NV': 'Carson City',
    'NH': 'Concord', 'NJ': 'Trenton', 'NM': 'Santa Fe', 'NY': 'Albany',
    'NC': 'Raleigh', 'ND': 'Bismarck', 'OH': 'Columbus', 'OK': 'Oklahoma City',
    'OR': 'Salem', 'PA': 'Harrisburg', 'RI': 'Providence', 'SC': 'Columbia',
    'SD': 'Pierre', 'TN': 'Nashville', 'TX': 'Austin', 'UT': 'Salt Lake City',
    'VT': 'Montpelier', 'VA': 'Richmond', 'WA': 'Olympia', 'WV': 'Charleston',
    'WI': 'Madison', 'WY': 'Cheyenne', 'DC': 'Washington',
}

# Top US cities by population — known and commonly typed.
# Tuples: (city, state, county) — county is primary or most populous for split cities.
TOP_CITIES = [
    ('New York', 'NY', 'New York'),
    ('Los Angeles', 'CA', 'Los Angeles'),
    ('Chicago', 'IL', 'Cook'),
    ('Houston', 'TX', 'Harris'),
    ('Phoenix', 'AZ', 'Maricopa'),
    ('Philadelphia', 'PA', 'Philadelphia'),
    ('San Antonio', 'TX', 'Bexar'),
    ('San Diego', 'CA', 'San Diego'),
    ('Dallas', 'TX', 'Dallas'),
    ('San Jose', 'CA', 'Santa Clara'),
    ('Austin', 'TX', 'Travis'),
    ('Jacksonville', 'FL', 'Duval'),
    ('Fort Worth', 'TX', 'Tarrant'),
    ('Columbus', 'OH', 'Franklin'),
    ('Indianapolis', 'IN', 'Marion'),
    ('Charlotte', 'NC', 'Mecklenburg'),
    ('San Francisco', 'CA', 'San Francisco'),
    ('Seattle', 'WA', 'King'),
    ('Denver', 'CO', 'Denver'),
    ('Washington', 'DC', 'District of Columbia'),
    ('Nashville', 'TN', 'Davidson'),
    ('Oklahoma City', 'OK', 'Oklahoma'),
    ('El Paso', 'TX', 'El Paso'),
    ('Boston', 'MA', 'Suffolk'),
    ('Portland', 'OR', 'Multnomah'),
    ('Las Vegas', 'NV', 'Clark'),
    ('Detroit', 'MI', 'Wayne'),
    ('Memphis', 'TN', 'Shelby'),
    ('Louisville', 'KY', 'Jefferson'),
    ('Baltimore', 'MD', 'Baltimore City'),
    ('Milwaukee', 'WI', 'Milwaukee'),
    ('Albuquerque', 'NM', 'Bernalillo'),
    ('Tucson', 'AZ', 'Pima'),
    ('Fresno', 'CA', 'Fresno'),
    ('Sacramento', 'CA', 'Sacramento'),
    ('Kansas City', 'MO', 'Jackson'),
    ('Mesa', 'AZ', 'Maricopa'),
    ('Atlanta', 'GA', 'Fulton'),
    ('Omaha', 'NE', 'Douglas'),
    ('Colorado Springs', 'CO', 'El Paso'),
    ('Raleigh', 'NC', 'Wake'),
    ('Long Beach', 'CA', 'Los Angeles'),
    ('Virginia Beach', 'VA', 'Virginia Beach'),
    ('Miami', 'FL', 'Miami-Dade'),
    ('Oakland', 'CA', 'Alameda'),
    ('Minneapolis', 'MN', 'Hennepin'),
    ('Tulsa', 'OK', 'Tulsa'),
    ('Bakersfield', 'CA', 'Kern'),
    ('Wichita', 'KS', 'Sedgwick'),
    ('Arlington', 'TX', 'Tarrant'),
    ('Aurora', 'CO', 'Arapahoe'),
    ('Tampa', 'FL', 'Hillsborough'),
    ('New Orleans', 'LA', 'Orleans'),
    ('Cleveland', 'OH', 'Cuyahoga'),
    ('Honolulu', 'HI', 'Honolulu'),
    ('Anaheim', 'CA', 'Orange'),
    ('Lexington', 'KY', 'Fayette'),
    ('Stockton', 'CA', 'San Joaquin'),
    ('Corpus Christi', 'TX', 'Nueces'),
    ('Henderson', 'NV', 'Clark'),
    ('Riverside', 'CA', 'Riverside'),
    ('Newark', 'NJ', 'Essex'),
    ('Saint Paul', 'MN', 'Ramsey'),
    ('Santa Ana', 'CA', 'Orange'),
    ('Cincinnati', 'OH', 'Hamilton'),
    ('Irvine', 'CA', 'Orange'),
    ('Orlando', 'FL', 'Orange'),
    ('Pittsburgh', 'PA', 'Allegheny'),
    ('Saint Louis', 'MO', 'St. Louis City'),
    ('Greensboro', 'NC', 'Guilford'),
    ('Jersey City', 'NJ', 'Hudson'),
    ('Anchorage', 'AK', 'Anchorage'),
    ('Lincoln', 'NE', 'Lancaster'),
    ('Plano', 'TX', 'Collin'),
    ('Durham', 'NC', 'Durham'),
    ('Buffalo', 'NY', 'Erie'),
    ('Chandler', 'AZ', 'Maricopa'),
    ('Chula Vista', 'CA', 'San Diego'),
    ('Toledo', 'OH', 'Lucas'),
    ('Madison', 'WI', 'Dane'),
    ('Gilbert', 'AZ', 'Maricopa'),
    ('Reno', 'NV', 'Washoe'),
    ('Fort Wayne', 'IN', 'Allen'),
    ('North Las Vegas', 'NV', 'Clark'),
    ('St. Petersburg', 'FL', 'Pinellas'),
    ('Lubbock', 'TX', 'Lubbock'),
    ('Laredo', 'TX', 'Webb'),
    ('Norfolk', 'VA', 'Norfolk'),
    ('Glendale', 'AZ', 'Maricopa'),
    ('Hialeah', 'FL', 'Miami-Dade'),
    ('Garland', 'TX', 'Dallas'),
    ('Scottsdale', 'AZ', 'Maricopa'),
    ('Chesapeake', 'VA', 'Chesapeake'),
    ('Irving', 'TX', 'Dallas'),
    ('Winston-Salem', 'NC', 'Forsyth'),
    ('Fremont', 'CA', 'Alameda'),
    ('Boise', 'ID', 'Ada'),
    ('Richmond', 'VA', 'Richmond City'),
    ('San Bernardino', 'CA', 'San Bernardino'),
    ('Birmingham', 'AL', 'Jefferson'),
    ('Spokane', 'WA', 'Spokane'),
    ('Rochester', 'NY', 'Monroe'),
    ('Des Moines', 'IA', 'Polk'),
    ('Modesto', 'CA', 'Stanislaus'),
    ('Fayetteville', 'NC', 'Cumberland'),
    ('Tacoma', 'WA', 'Pierce'),
    ('Oxnard', 'CA', 'Ventura'),
    ('Fontana', 'CA', 'San Bernardino'),
    ('Columbus', 'GA', 'Muscogee'),
    ('Montgomery', 'AL', 'Montgomery'),
    ('Moreno Valley', 'CA', 'Riverside'),
    ('Shreveport', 'LA', 'Caddo'),
    ('Aurora', 'IL', 'Kane'),
    ('Yonkers', 'NY', 'Westchester'),
    ('Akron', 'OH', 'Summit'),
    ('Huntington Beach', 'CA', 'Orange'),
    ('Little Rock', 'AR', 'Pulaski'),
    ('Augusta', 'GA', 'Richmond'),
    ('Amarillo', 'TX', 'Potter'),
    ('Glendale', 'CA', 'Los Angeles'),
    ('Mobile', 'AL', 'Mobile'),
    ('Grand Rapids', 'MI', 'Kent'),
    ('Salt Lake City', 'UT', 'Salt Lake'),
    ('Tallahassee', 'FL', 'Leon'),
    ('Huntsville', 'AL', 'Madison'),
    ('Grand Prairie', 'TX', 'Dallas'),
    ('Knoxville', 'TN', 'Knox'),
    ('Worcester', 'MA', 'Worcester'),
    ('Newport News', 'VA', 'Newport News'),
    ('Brownsville', 'TX', 'Cameron'),
    ('Overland Park', 'KS', 'Johnson'),
    ('Santa Clarita', 'CA', 'Los Angeles'),
    ('Providence', 'RI', 'Providence'),
    ('Garden Grove', 'CA', 'Orange'),
    ('Chattanooga', 'TN', 'Hamilton'),
    ('Oceanside', 'CA', 'San Diego'),
    ('Jackson', 'MS', 'Hinds'),
    ('Fort Lauderdale', 'FL', 'Broward'),
    ('Santa Rosa', 'CA', 'Sonoma'),
    ('Rancho Cucamonga', 'CA', 'San Bernardino'),
    ('Port St. Lucie', 'FL', 'St. Lucie'),
    ('Tempe', 'AZ', 'Maricopa'),
    ('Ontario', 'CA', 'San Bernardino'),
    ('Vancouver', 'WA', 'Clark'),
    ('Cape Coral', 'FL', 'Lee'),
    ('Sioux Falls', 'SD', 'Minnehaha'),
    ('Springfield', 'MO', 'Greene'),
    ('Peoria', 'AZ', 'Maricopa'),
    ('Pembroke Pines', 'FL', 'Broward'),
    ('Elk Grove', 'CA', 'Sacramento'),
    ('Salem', 'OR', 'Marion'),
    ('Lancaster', 'CA', 'Los Angeles'),
    ('Corona', 'CA', 'Riverside'),
    ('Eugene', 'OR', 'Lane'),
    ('Palmdale', 'CA', 'Los Angeles'),
    ('Salinas', 'CA', 'Monterey'),
    ('Springfield', 'MA', 'Hampden'),
    ('Pasadena', 'TX', 'Harris'),
    ('Fort Collins', 'CO', 'Larimer'),
    ('Hayward', 'CA', 'Alameda'),
    ('Pomona', 'CA', 'Los Angeles'),
    ('Cary', 'NC', 'Wake'),
    ('Rockford', 'IL', 'Winnebago'),
    ('Alexandria', 'VA', 'Alexandria'),
    ('Escondido', 'CA', 'San Diego'),
    ('McKinney', 'TX', 'Collin'),
    ('Kansas City', 'KS', 'Wyandotte'),
    ('Joliet', 'IL', 'Will'),
    ('Sunnyvale', 'CA', 'Santa Clara'),
    ('Torrance', 'CA', 'Los Angeles'),
    ('Bridgeport', 'CT', 'Fairfield'),
    ('Lakewood', 'CO', 'Jefferson'),
    ('Hollywood', 'FL', 'Broward'),
    ('Paterson', 'NJ', 'Passaic'),
    ('Naperville', 'IL', 'DuPage'),
    ('Syracuse', 'NY', 'Onondaga'),
    ('Mesquite', 'TX', 'Dallas'),
    ('Dayton', 'OH', 'Montgomery'),
    ('Savannah', 'GA', 'Chatham'),
    ('Clarksville', 'TN', 'Montgomery'),
    ('Orange', 'CA', 'Orange'),
    ('Pasadena', 'CA', 'Los Angeles'),
    ('Fullerton', 'CA', 'Orange'),
    ('Killeen', 'TX', 'Bell'),
    ('Frisco', 'TX', 'Collin'),
    ('Hampton', 'VA', 'Hampton'),
    ('McAllen', 'TX', 'Hidalgo'),
    ('Warren', 'MI', 'Macomb'),
    ('Bellevue', 'WA', 'King'),
    ('West Valley City', 'UT', 'Salt Lake'),
    ('Columbia', 'SC', 'Richland'),
    ('Olathe', 'KS', 'Johnson'),
    ('Sterling Heights', 'MI', 'Macomb'),
    ('New Haven', 'CT', 'New Haven'),
    ('Miramar', 'FL', 'Broward'),
    ('Waco', 'TX', 'McLennan'),
    ('Thousand Oaks', 'CA', 'Ventura'),
    ('Cedar Rapids', 'IA', 'Linn'),
    ('Charleston', 'SC', 'Charleston'),
    ('Visalia', 'CA', 'Tulare'),
    ('Topeka', 'KS', 'Shawnee'),
    ('Elizabeth', 'NJ', 'Union'),
    ('Gainesville', 'FL', 'Alachua'),
    ('Thornton', 'CO', 'Adams'),
    ('Roseville', 'CA', 'Placer'),
    ('Carrollton', 'TX', 'Dallas'),
    ('Coral Springs', 'FL', 'Broward'),
    ('Stamford', 'CT', 'Fairfield'),
    ('Simi Valley', 'CA', 'Ventura'),
    ('Concord', 'CA', 'Contra Costa'),
    ('Hartford', 'CT', 'Hartford'),
    ('Kent', 'WA', 'King'),
    ('Lafayette', 'LA', 'Lafayette'),
    ('Midland', 'TX', 'Midland'),
    ('Surprise', 'AZ', 'Maricopa'),
    ('Denton', 'TX', 'Denton'),
    ('Victorville', 'CA', 'San Bernardino'),
    ('Evansville', 'IN', 'Vanderburgh'),
    ('Santa Clara', 'CA', 'Santa Clara'),
    ('Abilene', 'TX', 'Taylor'),
    ('Athens', 'GA', 'Clarke'),
    ('Vallejo', 'CA', 'Solano'),
    ('Allentown', 'PA', 'Lehigh'),
    ('Norman', 'OK', 'Cleveland'),
    ('Beaumont', 'TX', 'Jefferson'),
    ('Independence', 'MO', 'Jackson'),
    ('Murfreesboro', 'TN', 'Rutherford'),
    ('Ann Arbor', 'MI', 'Washtenaw'),
    ('Springfield', 'IL', 'Sangamon'),
    ('Berkeley', 'CA', 'Alameda'),
    ('Peoria', 'IL', 'Peoria'),
    ('Provo', 'UT', 'Utah'),
    ('El Monte', 'CA', 'Los Angeles'),
    ('Columbia', 'MO', 'Boone'),
    ('Lansing', 'MI', 'Ingham'),
    ('Fargo', 'ND', 'Cass'),
    ('Downey', 'CA', 'Los Angeles'),
    ('Costa Mesa', 'CA', 'Orange'),
    ('Wilmington', 'NC', 'New Hanover'),
    ('Arvada', 'CO', 'Jefferson'),
    ('Inglewood', 'CA', 'Los Angeles'),
    ('Miami Gardens', 'FL', 'Miami-Dade'),
    ('Carlsbad', 'CA', 'San Diego'),
    ('Westminster', 'CO', 'Adams'),
    ('Rochester', 'MN', 'Olmsted'),
    ('Odessa', 'TX', 'Ector'),
    ('Manchester', 'NH', 'Hillsborough'),
    ('Elgin', 'IL', 'Kane'),
    ('West Jordan', 'UT', 'Salt Lake'),
    ('Round Rock', 'TX', 'Williamson'),
    ('Clearwater', 'FL', 'Pinellas'),
    ('Waterbury', 'CT', 'New Haven'),
    ('Gresham', 'OR', 'Multnomah'),
    ('Fairfield', 'CA', 'Solano'),
    ('Billings', 'MT', 'Yellowstone'),
    ('Lowell', 'MA', 'Middlesex'),
    ('Ventura', 'CA', 'Ventura'),
    ('Pueblo', 'CO', 'Pueblo'),
    ('High Point', 'NC', 'Guilford'),
    ('West Covina', 'CA', 'Los Angeles'),
    ('Richmond', 'CA', 'Contra Costa'),
    ('Murrieta', 'CA', 'Riverside'),
    ('Cambridge', 'MA', 'Middlesex'),
    ('Antioch', 'CA', 'Contra Costa'),
    ('Temecula', 'CA', 'Riverside'),
    ('Norwalk', 'CA', 'Los Angeles'),
    ('Centennial', 'CO', 'Arapahoe'),
    ('Everett', 'WA', 'Snohomish'),
    ('Palm Bay', 'FL', 'Brevard'),
    ('Wichita Falls', 'TX', 'Wichita'),
    ('Green Bay', 'WI', 'Brown'),
    ('Daly City', 'CA', 'San Mateo'),
    ('Burbank', 'CA', 'Los Angeles'),
    ('Richardson', 'TX', 'Dallas'),
    ('Pompano Beach', 'FL', 'Broward'),
    ('North Charleston', 'SC', 'Charleston'),
    ('Broken Arrow', 'OK', 'Tulsa'),
    ('Boulder', 'CO', 'Boulder'),
    ('West Palm Beach', 'FL', 'Palm Beach'),
    ('Santa Maria', 'CA', 'Santa Barbara'),
    ('El Cajon', 'CA', 'San Diego'),
    ('Davenport', 'IA', 'Scott'),
    ('Rialto', 'CA', 'San Bernardino'),
    ('Edison', 'NJ', 'Middlesex'),
    ('Las Cruces', 'NM', 'Doña Ana'),
    ('San Mateo', 'CA', 'San Mateo'),
    ('Lewisville', 'TX', 'Denton'),
    ('South Bend', 'IN', 'Saint Joseph'),
    ('Lakeland', 'FL', 'Polk'),
    ('Erie', 'PA', 'Erie'),
    ('Tyler', 'TX', 'Smith'),
    ('Pearland', 'TX', 'Brazoria'),
    ('College Station', 'TX', 'Brazos'),
    ('Kenosha', 'WI', 'Kenosha'),
    ('Sandy Springs', 'GA', 'Fulton'),
    ('Clovis', 'CA', 'Fresno'),
    ('Flint', 'MI', 'Genesee'),
    ('Roanoke', 'VA', 'Roanoke'),
    ('Albany', 'NY', 'Albany'),
    ('Jurupa Valley', 'CA', 'Riverside'),
    ('Compton', 'CA', 'Los Angeles'),
    # Extra Florida cities we care about
    ('Melbourne', 'FL', 'Brevard'),
    ('Sarasota', 'FL', 'Sarasota'),
    ('Deltona', 'FL', 'Volusia'),
    ('Plantation', 'FL', 'Broward'),
    ('Largo', 'FL', 'Pinellas'),
    ('Deerfield Beach', 'FL', 'Broward'),
    ('Boca Raton', 'FL', 'Palm Beach'),
    ('Sunrise', 'FL', 'Broward'),
    ('Davie', 'FL', 'Broward'),
    ('Boynton Beach', 'FL', 'Palm Beach'),
    ('Delray Beach', 'FL', 'Palm Beach'),
    ('Kissimmee', 'FL', 'Osceola'),
    ('Homestead', 'FL', 'Miami-Dade'),
    ('Doral', 'FL', 'Miami-Dade'),
    ('North Miami', 'FL', 'Miami-Dade'),
    ('Weston', 'FL', 'Broward'),
    ('Ocala', 'FL', 'Marion'),
    ('Daytona Beach', 'FL', 'Volusia'),
    ('Cocoa', 'FL', 'Brevard'),
    ('Titusville', 'FL', 'Brevard'),
    ('Cape Canaveral', 'FL', 'Brevard'),
    ('Merritt Island', 'FL', 'Brevard'),
    ('Satellite Beach', 'FL', 'Brevard'),
    ('Indialantic', 'FL', 'Brevard'),
    ('Indian Harbour Beach', 'FL', 'Brevard'),
    ('West Melbourne', 'FL', 'Brevard'),
    ('Melbourne Beach', 'FL', 'Brevard'),
    ('Rockledge', 'FL', 'Brevard'),
    ('Viera', 'FL', 'Brevard'),
    ('Suntree', 'FL', 'Brevard'),
    ('Naples', 'FL', 'Collier'),
    ('Key West', 'FL', 'Monroe'),
    ('Fort Myers', 'FL', 'Lee'),
    ('Vero Beach', 'FL', 'Indian River'),
    ('Fort Pierce', 'FL', 'St. Lucie'),
    ('Stuart', 'FL', 'Martin'),
    ('Jupiter', 'FL', 'Palm Beach'),
    ('Winter Park', 'FL', 'Orange'),
    ('Winter Garden', 'FL', 'Orange'),
    ('Ormond Beach', 'FL', 'Volusia'),
    ('Port Orange', 'FL', 'Volusia'),
    ('New Smyrna Beach', 'FL', 'Volusia'),
    ('Panama City', 'FL', 'Bay'),
    ('Pensacola', 'FL', 'Escambia'),
    ('Destin', 'FL', 'Okaloosa'),
    ('Crestview', 'FL', 'Okaloosa'),
    ('DeLand', 'FL', 'Volusia'),
    ('Sanford', 'FL', 'Seminole'),
    ('Altamonte Springs', 'FL', 'Seminole'),
    ('Oviedo', 'FL', 'Seminole'),
    ('Brandon', 'FL', 'Hillsborough'),
    ('Riverview', 'FL', 'Hillsborough'),
    ('Bradenton', 'FL', 'Manatee'),
]

# All 67 Florida counties
FL_COUNTIES = [
    'Alachua', 'Baker', 'Bay', 'Bradford', 'Brevard', 'Broward', 'Calhoun',
    'Charlotte', 'Citrus', 'Clay', 'Collier', 'Columbia', 'DeSoto', 'Dixie',
    'Duval', 'Escambia', 'Flagler', 'Franklin', 'Gadsden', 'Gilchrist',
    'Glades', 'Gulf', 'Hamilton', 'Hardee', 'Hendry', 'Hernando', 'Highlands',
    'Hillsborough', 'Holmes', 'Indian River', 'Jackson', 'Jefferson',
    'Lafayette', 'Lake', 'Lee', 'Leon', 'Levy', 'Liberty', 'Madison',
    'Manatee', 'Marion', 'Martin', 'Miami-Dade', 'Monroe', 'Nassau',
    'Okaloosa', 'Okeechobee', 'Orange', 'Osceola', 'Palm Beach', 'Pasco',
    'Pinellas', 'Polk', 'Putnam', 'St. Johns', 'St. Lucie', 'Santa Rosa',
    'Sarasota', 'Seminole', 'Sumter', 'Suwannee', 'Taylor', 'Union',
    'Volusia', 'Wakulla', 'Walton', 'Washington',
]


def slugify(s):
    return s.lower().replace(' ', '-').replace('.', '').replace(',', '').replace("'", '')


def build():
    out = {'states': [], 'counties': [], 'cities': []}

    # States
    for code, name in STATES.items():
        out['states'].append({
            'code': code,
            'name': name,
            'display': name,
            'aliases': list({
                code.lower(),
                name.lower(),
                'state of ' + name.lower(),
            }),
        })

    # Counties (FL only — our deepest state)
    for county in FL_COUNTIES:
        display = f'{county} County, Florida'
        out['counties'].append({
            'name': county,
            'state': 'FL',
            'display': display,
            'aliases': list({
                county.lower(),
                county.lower() + ' county',
                county.lower() + ', fl',
                county.lower() + ', florida',
                county.lower() + ' county fl',
                county.lower() + ' county florida',
            }),
        })

    # State capitals (add aliases so 'Nashville' matches)
    city_entries = list(TOP_CITIES)
    added_caps = set((c.lower(), s) for c, s, _ in city_entries)
    for state_code, capital in STATE_CAPITALS.items():
        if (capital.lower(), state_code) not in added_caps:
            # No county info for pure capitals — hand-fill the known ones above.
            pass

    # Cities
    for city, state, county in city_entries:
        county_suffix = f' ({county} County)' if county else ''
        display = f'{city}, {STATES[state]}{county_suffix}'
        aliases = set([
            city.lower(),
            city.lower() + ', ' + state.lower(),
            city.lower() + ' ' + state.lower(),
            city.lower() + ', ' + STATES[state].lower(),
            city.lower() + ' ' + STATES[state].lower(),
        ])
        out['cities'].append({
            'name': city,
            'state': state,
            'county': county,
            'display': display,
            'aliases': list(aliases),
        })

    with open(OUT, 'w') as f:
        json.dump(out, f, separators=(',', ':'))
    print(f'Wrote {OUT}')
    print(f'  States: {len(out["states"])}')
    print(f'  Counties (FL only): {len(out["counties"])}')
    print(f'  Cities: {len(out["cities"])}')
    print(f'  Total bytes: {OUT.stat().st_size:,}')


if __name__ == '__main__':
    build()
