'use strict';

const { fieldManual: module01FieldManual } = require('./module-01.field-manual.js');
const { fieldManual: module02FieldManual } = require('./module-02.field-manual.js');
const { fieldManual: module03FieldManual } = require('./module-03.field-manual.js');
const { fieldManual: module04FieldManual } = require('./module-04.field-manual.js');
const { fieldManual: module05FieldManual } = require('./module-05.field-manual.js');
const { fieldManual: module06FieldManual } = require('./module-06.field-manual.js');
const { fieldManual: module07FieldManual } = require('./module-07.field-manual.js');

const sharedSupport =`This course is formation for a basically safe marriage. It is not crisis care, clinical treatment, addiction recovery, trauma care, or a substitute for qualified pastoral counsel. If there is immediate danger, contact emergency services. Do not use joint exercises to force disclosure or reconciliation where coercion, threats, violence, or fear of retaliation are present. A husband must never use Scripture, forgiveness, headship, money, children, or course completion to demand access, silence concern, or prevent help.`;

const commonResources = [
  { label: 'Read Scripture in the MOOP Bible Translation Engine on usmcmin.org', href: 'https://usmcmin.org/bible.html' },
  
];

const publishedModuleIds = new Set(['m01', 'm02', 'm03', 'm04', 'm05', 'm06', 'm07']);

const course = {
  id: 'tmc-husband-v1',
  contentVersion: 1,
  title: 'The Husband Course',
  subtitle: 'Seven modules. One required action each week.',
  publishedModuleIds,
  status: 'All seven modules are live. Free, local-only progress; no account, no sync. Modules 1–3 include optional study aids.',
  promise: 'Each module tells you exactly what to do this week, with an observable finish line your wife could notice. Progress stays only in this browser on this device.',
  howItWorks: [
    { title: 'Read the module', body: 'Short opening, Scripture anchor, and 3–5 numbered tasks. About 45–60 minutes.' },
    { title: 'Complete the action', body: 'One required exercise with a visible finish line. Husband-owned; her participation is invited, not demanded.' },
    { title: 'Optional depth', body: 'Optional study aids, a knowledge check, and conversation prompts if she is willing.' }
  ],
  modules: [
    {
      id: 'm01', number: 1, slug: 'module-01.html', title: 'Build the Foundation',
      question: 'What am I building my marriage on, and what am I personally responsible to reinforce?',
      fieldActionSummary: 'Weekly 20-minute marriage check-in + one act of care',
      timeEstimate: '45–60 min + one check-in this week',
      missionBrief: [
        `A strong marriage is not built by discovering the perfect spouse or by waiting for a season with fewer demands. It is built by two imperfect people practicing truth, faithfulness, repentance, and care under ordinary pressure. For a husband, the first assignment is not to grade his wife. It is to ask what kind of man he is becoming before God and what his repeated conduct is placing into the home. Promises at the altar matter, but daily patterns give those promises visible shape. The foundation is reinforced when your wife can reasonably expect that your words will match your actions, that problems can be named, and that you will return after distraction or failure rather than disappear into defensiveness.`,
        `Christian covenant does not mean pretending everything is healthy. Covenant love tells the truth, protects the vulnerable, keeps rightful promises, and refuses both abandonment and domination. Christlike leadership cannot be measured by how efficiently a husband gets his way. It is measured by service, responsibility, self-control, and willingness to lay down pride. That means taking initiative without taking over. You can invite a check-in, arrange childcare, put away the phone, and admit your part. You cannot command trust, schedule your wife’s emotions, or make her perform closeness. Faithful initiative creates room for honest response; control punishes response when it is inconvenient.`,
        `Many couples rely on accidental communication. They speak about bills, children, calendars, repairs, and errands, then wonder why their friendship feels thin. Logistics are necessary, but they are not the whole relationship. A short weekly check-in creates a protected place to notice what routine conversation misses. Its purpose is not to solve every concern in twenty minutes. Its purpose is to practice attention: gratitude, current pressure, one practical need, and one next step. A reliable small meeting usually serves a marriage better than an occasional dramatic promise because it lowers the cost of speaking before resentment has accumulated.`,
        `Your first check-in should be modest. Ask when twenty uninterrupted minutes would be welcome; do not announce a mandatory meeting. Begin with one concrete appreciation that is not flattery and not a preface to criticism. Ask what has felt heavy this week. Listen without correcting details. Share one pressure of your own without making her responsible to fix it. Then identify one small action you can own before the next check-in. End on time unless both of you freely choose to continue. A trustworthy rhythm respects the boundary it promises, including the boundary that either spouse may need a pause or a different time.`,
        `Consistency matters more than polish. You may forget a question, feel awkward, or discover that the first scheduled time does not work. Do not turn imperfection into an excuse to quit. Repair the miss, choose another time, and keep the practice light enough to repeat. At the same time, do not make consistency into surveillance. A check-in is not a performance review, a spiritual inspection, or evidence that you are now entitled to praise. The fruit should appear outside the meeting: you remember what was said, carry your agreed responsibility, and become easier to approach.`,
        `A foundation also includes outside support. Isolation makes ordinary stress heavier and serious danger easier to hide. Healthy couples benefit from wise friends, mature pastoral care, and qualified professional help when a problem exceeds their tools. Seeking counsel is not a confession that marriage has failed. It can be an act of stewardship. Choose helpers who respect truth and safety, do not minimize abuse, do not demand instant reconciliation, and do not recruit an audience against your spouse. Confidentiality, competence, and clear boundaries matter more than a helper’s charisma.`,
        `Measure your responsibility by what you can actually do. You can govern your tone, tell the truth about money, return when you promised, apologize without qualifications, protect rest, and seek help for your own sin or illness. You cannot guarantee your wife’s reaction or use your effort to erase her agency. If she does not want the check-in today, respond with curiosity rather than punishment. Ask whether a different format or time would feel better. Continue becoming dependable without keeping a secret score. Love is not passivity, but neither is it a transaction that purchases an outcome.`,
        `This week, do one small thing once rather than planning something ambitious you will not repeat. Establish a twenty-minute check-in and complete it once. Put the next one on your own calendar only after asking whether the rhythm served both of you. Write no private report about her answers and store no sensitive details in this course. Remember the finish line: you made a respectful invitation, listened, named one responsibility, and followed through. That simple loop; invite, attend, own, act, return; will support every module that follows. The goal is not a flawless meeting. The goal is a home where faithful attention becomes normal.`
      ],
      scripture: [
        { reference: 'Matthew 7:24–27', note: 'Jesus closes the Sermon on the Mount by connecting hearing with doing. The image concerns obedient discipleship, not a promise that a faithful husband can control every outcome.' },
        { reference: 'Ephesians 5:21, 25–33', note: 'Verse 21 opens a household code; paired commands to wives and husbands, children and parents, servants and masters; and Paul never reverses the direction inside a pair. He does not tell husbands to submit to their wives; he tells them to love as Christ loved the church. A wife’s submission and a husband’s self-giving love are two distinct callings rather than one symmetrical rule, and both spouses answer to Christ. The passage gives no warrant for coercion, entitlement, or concealment of harm.' },
        { reference: 'James 1:19–22', note: 'Quick listening and practiced obedience expose the gap between religious speech and embodied faithfulness.' }
      ],
      fairInsight: `The source research rightly treats marriage as something couples cultivate deliberately rather than merely feel. Its emphasis on regular connection, friendship, and habits gives husbands practical handles instead of vague inspiration. A scheduled conversation can make care visible and prevent logistics from consuming every interaction.`,
      caution: `Relationship habits help basically safe couples; they do not repair violence, coercive control, active betrayal, or addiction by themselves. “Covenant” must never be used to trap a spouse in danger. A husband’s initiative is not authority to compel participation, and symmetrical “both sides” language is dishonest when one person is abusing power.`,
      selfCheck: [
        'Where do my promises and repeated habits currently disagree?',
        'When my wife raises a concern, do I become curious, defensive, absent, or controlling?',
        'What household pressure can I take responsibility for without waiting to be managed?',
        'Who is one wise, safe person I could approach before a crisis grows?'
      ],
      fieldAction: { title: 'Complete the first twenty-minute marriage check-in', steps: ['Ask for a mutually workable time.', 'Share one specific appreciation.', 'Listen to one current pressure without defending.', 'Choose one action you personally own and a time to do it.'], finishLine: 'The check-in occurred, ended respectfully, and your owned action is scheduled or finished.' },
      conversation: ['Would a brief weekly check-in serve you, and what would make it feel safe rather than burdensome?', 'What is one thing I did this week that helped?', 'What is one pressure you want me to understand; not necessarily solve?', 'What one action would be most useful for me to own before we talk again?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module01FieldManual
    },
    {
      id: 'm02', number: 2, slug: 'module-02.html', title: 'Communicate to Understand',
      question: 'Do I listen to understand, or listen to answer and defend?',
      fieldActionSummary: 'One 15-minute listen-back conversation',
      timeEstimate: '45–60 min + one listen-back',
      missionBrief: [
        `Listening is not silence while preparing a rebuttal. It is disciplined attention offered long enough to understand what another person means, values, fears, or needs. Husbands often mistake problem-solving for love: identify the issue, propose the fix, and move on. A solution can be useful, but an early solution may communicate that the speaker’s experience is an obstacle to remove. Understanding comes first. Your wife is not asking you to surrender judgment or agree with every conclusion. She is asking, at minimum, to know whether her words reached you without being filtered immediately through self-protection.`,
        `The core practice is listen-back. One spouse speaks briefly about one concern. The listener summarizes both content and significance in his own words, then asks whether he understood. He does not cross-examine, diagnose, correct chronology, quote earlier statements, or introduce his counter-case. If the summary misses, he tries again. Only after the speaker says the summary is substantially accurate does the listener ask whether she wants empathy, ideas, action, or simply time. This process may feel slow because it interrupts the habits that usually make a conversation fast and fruitless.`,
        `Accurate restatement is not agreement. You can say, “You felt alone when I stayed on my phone after you asked for help, and it made you wonder whether your exhaustion mattered to me,” without yet deciding every disputed fact. Acknowledging impact does not require inventing intent, and explaining intent does not cancel impact. Mature communication can hold both. If you intended to finish urgent work and your conduct still landed as indifference, truth includes the deadline and the loneliness. Defensiveness edits reality until only your motives remain.`,
        `Pay attention to nonverbal conduct. A gentle script cannot compensate for eye-rolling, pacing, phone checking, looming over someone, blocking an exit, or using silence as punishment. Sit at a respectful distance. Keep the way out clear. Lower your volume. If either person becomes flooded, name a pause and a specific return time rather than storming off indefinitely. A communication tool is trustworthy only when refusal, correction, and pause are allowed. “We must finish this now” can become coercive even when the topic itself is ordinary.`,
        `Curiosity uses open questions and does not smuggle in a verdict. “What part felt most difficult?” invites detail. “Why are you always so negative?” is an accusation wearing a question mark. Avoid absolute words such as always and never unless they are literally true. Stay with one event at a time. Ask what the concern means to her instead of assuming your interpretation is obvious. Then notice whether you are collecting facts for care or collecting ammunition for later. The posture beneath the technique determines whether the technique builds trust.`,
        `Your own perspective matters, but timing matters too. After understanding has been confirmed, ask permission to share it. Speak from your experience and responsibility. Replace “You make me” with a more truthful account of what happened inside you and what you chose to do. Name concrete behavior rather than attacking character. “I felt embarrassed and withdrew; I should have told you I needed ten minutes” gives something to work with. “You are impossible” offers only contempt. Truth should become more specific as a conversation gets harder, not more sweeping.`,
        `Differences in processing speed are not moral rank. One spouse may find words quickly; another may need time. One may want eye contact; another may listen better while walking. Culture, temperament, neurodivergence, trauma, hearing loss, language, fatigue, and stress all shape communication. Adapt the form while protecting the aim: voluntary, respectful understanding. A written note may open a conversation but should not become an unanswerable manifesto. A pause may regulate the body but should not become abandonment. The question is whether the adaptation keeps both truth and connection possible.`,
        `Listening also includes remembering. If your wife trusted you with a concern, write the action you own in your own task system without recording her sensitive details. Return with evidence of follow-through rather than making her raise the subject again. If you need clarification, ask briefly and respectfully. Repeatedly forgetting what matters to her can make even a polished listening exercise feel theatrical. Attention becomes dependable when it moves from hearing, to understanding, to appropriate action, and then back to a simple check: “Did that address what you meant?”`,
        `This week, choose one low-to-moderate concern, not the most explosive issue in your marriage. Ask whether your wife is willing to speak for five minutes while you practice listening back. Summarize, ask what you missed, revise, and let her confirm accuracy. Do not demand that she perform the same exercise. Your required action is complete when she can say you represented her concern fairly, even if you still differ. The win is not persuasion. It is proving that disagreement does not have to erase her voice or your self-control.`
      ],
      scripture: [
        { reference: 'James 1:19–20', note: 'Quick listening and slow anger are practices of righteousness, not tactics for winning an argument.' },
        { reference: 'Proverbs 18:13, 17', note: 'Answering before listening is folly, and the first account still deserves examination. Humility attends before concluding.' },
        { reference: 'Ephesians 4:25, 29', note: 'Truthful speech should fit the need and build up; truth is not permission for contempt or verbal force.' }
      ],
      fairInsight: `The source research’s strongest communication contribution is practical listening: turn toward the speaker, avoid interruption, acknowledge emotion, and clarify before replying. These behaviors reduce mind-reading and give couples a repeatable alternative to parallel monologues.`,
      caution: `Communication methods assume enough safety for honest speech. They can fail where disclosure is punished, monitored, or weaponized. Not every problem is a misunderstanding; sometimes the issue is deception, intimidation, addiction, or entrenched injustice. Better phrasing cannot substitute for accountability or confidential help.`,
      selfCheck: ['What do I do in the first ten seconds after hearing criticism?', 'Do I summarize my wife fairly, or use a weaker version that is easy to dismiss?', 'Which nonverbal habit of mine makes listening less believable?', 'Can I ask whether she wants empathy, ideas, or action before choosing for her?'],
      fieldAction: { title: 'Use one listen-back conversation', steps: ['Choose one manageable concern and ask consent to practice.', 'Listen without interruption for up to five minutes.', 'Restate content and significance in your own words.', 'Ask what you missed and revise before responding.'], finishLine: 'Your wife confirms that your summary represents her concern accurately enough, without being required to agree with you or repeat the exercise.' },
      conversation: ['Is now a workable time for me to listen without trying to fix?', 'What part of this matters most to you?', 'What did I miss or distort in my summary?', 'Would empathy, an idea, a specific action, or more time be most helpful?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module02FieldManual
    },
    {
      id: 'm03', number: 3, slug: 'module-03.html', title: 'Fight the Problem, Not Each Other',
      question: 'What conflict pattern do I bring into the marriage?',
      fieldActionSummary: 'Pause-and-return rule + one written decision',
      timeEstimate: '45–60 min + one conflict practice',
      missionBrief: [
        `Conflict is not proof that a marriage is defective. Two adults with different histories, bodies, expectations, responsibilities, and limits will collide. The decisive question is not whether conflict appears but what the couple does when it does. A husband can bring courage to conflict by staying truthful and regulated without becoming passive or aggressive. Courage names a problem specifically, protects the other person’s dignity, and accepts a fair boundary. Cowardice may look loud and dominating, but it may also look like disappearing, refusing every conversation, or agreeing outwardly while retaliating later.`,
        `Begin by identifying your recurring move. Under pressure, do you pursue harder, withdraw without a return, lecture, become sarcastic, appease, keep score, bring in unrelated failures, or threaten the relationship? The pattern is not your permanent identity, and naming it is not self-condemnation. It gives you a point of intervention. “When I feel misunderstood, I speed up, raise my voice, and stack evidence” is more useful than “I am just passionate.” A description that protects your ego will not help you change your conduct.`,
        `Separate the problem from the person. Define the issue in observable terms: “We have exceeded the grocery plan three weeks in a row,” not “You are irresponsible.” Name your own contribution before assigning hers. Agree on the decision that actually needs to be made. Many arguments become endless because one spouse is discussing money, the other is discussing respect, and both are prosecuting ten years of history. A narrow agenda is not avoidance; it is a guardrail that makes honest work possible. Other concerns can receive their own time.`,
        `Bodies can become too activated for wise conversation. Faster heart rate, tunnel vision, shaking, heat, numbness, or an urge to flee may signal that the nervous system is overtaking reflective judgment. A pause is then an act of stewardship, not surrender, if it includes a return. Use plain words: “I am too activated to speak carefully. I will take twenty minutes and return at 7:40.” During the pause, do not compose a closing argument, text allies, drink, drive recklessly, or punish with silence. Breathe, walk, pray, and return when promised.`,
        `A pause rule must be negotiated before the next heated moment. Either spouse may call it. No following from room to room, blocking doors, taking phones, threatening children, or forcing eye contact. No indefinite disappearance. If the named return time becomes impossible, send a brief update and offer another specific time. If returning reliably is beyond your current skill, seek support. The rule is designed to protect conversation, not help the more avoidant spouse escape responsibility or help the more pursuing spouse compel access.`,
        `When you return, lower the ambition. You may not resolve the whole issue. Try to state one shared fact, one point of difference, and one next experiment. A temporary plan can be honest when it includes review. For example: “For the next two weeks we will each record unplanned purchases over an agreed amount, then revisit the budget.” Do not call compliance peace if fear produced it. A workable decision should be clear enough to observe and free enough that disagreement can still be voiced.`,
        `Repair what happens during conflict, not only the original topic. If you used contempt, mocked vulnerability, shouted, or failed to return, confess that specific conduct. Do not wait until the budget is solved to admit that your tone was wrong. Likewise, do not use apology to close the topic prematurely. “I am sorry I yelled, so can we drop it?” turns confession into a control tactic. Repair restores conditions for problem-solving; it does not erase the underlying concern or require immediate emotional recovery.`,
        `Watch for contempt, because it converts a disputed action into a verdict on a person’s worth. Mockery, sneering, disgust, hostile imitation, and jokes made at a spouse’s expense are not harmless communication styles. Stop them promptly and repair them specifically. Also reject spiritual escalation: invoking God as though your interpretation closes the discussion, demanding prayer while someone is frightened, or treating disagreement with you as rebellion against God. Scripture should bring your own conduct under judgment before it becomes language aimed at your wife. If children witness the conflict, protect them from being made messengers, referees, confidants, or allies. Repair age-appropriately without burdening them with adult details. Model humble return.`,
        `This week, name one recurring conflict pattern you personally bring. Share it without diagnosing your wife’s pattern. Propose a pause-and-return rule and ask what would make it fair. Then use the rule once in a real disagreement or rehearse it during a calm five-minute scenario if no conflict occurs. The finish line is not that you avoided discomfort. It is that you interrupted your habitual move, protected dignity, and returned at the agreed time ready to address one problem rather than attack one another.`
      ],
      scripture: [
        { reference: 'Proverbs 15:1, 18', note: 'Gentleness can turn down heat, while a hot temper multiplies conflict. Gentleness is strength under control, not silence about wrong.' },
        { reference: 'Ephesians 4:26–27, 31–32', note: 'Paul calls believers away from corrosive anger and toward kindness; the text does not require unsafe proximity or instant emotional closure.' },
        { reference: 'Romans 12:18', note: '“If possible, so far as it depends on you” recognizes both personal responsibility and the limit of controlling another person.' }
      ],
      fairInsight: `The source research helpfully normalizes differences and offers practical de-escalation: identify recurring cycles, soften the opening, take a break when flooded, and return to the issue. Treating the couple as a team against a problem can reduce blame in ordinary conflict.`,
      caution: `Team language becomes dangerous when it hides one-sided abuse. Violence, threats, coercive control, stalking, and intimidation are not merely a mutual “cycle.” A pause rule must never trap someone, block an exit, or require unsafe re-engagement. Couple exercises may be inappropriate until individual safety and accountability are established.`,
      selfCheck: ['What is my first predictable move when conflict becomes uncomfortable?', 'How do I justify behavior from myself that I would recognize as harmful from someone else?', 'Do my pauses include a trustworthy return, or become punishment and avoidance?', 'Can I state our current problem without attacking character or importing unrelated history?'],
      fieldAction: { title: 'Interrupt one recurring conflict pattern', steps: ['Name your own pattern in concrete behavior.', 'Agree that either spouse may call a pause.', 'Choose a minimum pause length and a specific return method.', 'Use or calmly rehearse the rule once, then review whether it felt fair.'], finishLine: 'You interrupted your usual pattern, honored physical and verbal boundaries, and returned at the promised time or communicated a specific revised time.' },
      conversation: ['When conflict rises, what behavior from me makes it harder to stay safe and engaged?', 'What words should either of us use to call a pause?', 'How long usually helps us regulate without turning into avoidance?', 'What would a reliable return look like?'],
      support: sharedSupport,
      resources: commonResources,
      // Module 3 is content-complete: the generator renders the full field manual
      // instead of the generic module template. See module-03.field-manual.js.
      fieldManual: module03FieldManual
    },
    {
      id: 'm04', number: 4, slug: 'module-04.html', title: 'Repair Hurt and Practice Forgiveness',
      question: 'Where do confession, restitution, boundaries, and forgiveness differ?',
      missionBrief: [
        `Hurt in marriage is not healed by saying the word forgiveness faster. Repair begins with truth. A husband who has caused harm must face what he did, the effect it had, and what responsibility now requires. He should not demand that his wife first prove perfect motives, perfect memory, or perfect calm. Confession is not self-hatred; it is agreement with reality before God and the person harmed. It becomes credible when it is specific, unqualified, and followed by change that can be observed over time.`,
        `A complete apology names the action without hiding behind passive language. “I disclosed private information to my friend” is clearer than “Things were shared.” It acknowledges likely impact without dictating the other person’s feelings. It does not contain “but,” a counter-accusation, or a request for reassurance. It asks what repair may be appropriate while accepting that the harmed spouse may need time. The goal is not to produce the sentence “I forgive you.” The goal is to become truthful and to stop adding pressure to the original injury.`,
        `Restitution addresses what can be restored. If money was hidden, disclosure and a transparent financial plan may be needed. If a commitment was repeatedly broken, new accountability may be needed. If privacy was violated, the husband may need to correct the story with those who heard it. Some losses cannot be undone, and symbolic gestures cannot purchase trust. Restitution does not control the timeline of healing; it demonstrates that repentance is willing to bear cost rather than merely seek relief from guilt.`,
        `Forgiveness, reconciliation, and trust are related but distinct. Forgiveness can release personal vengeance to God and refuse to nurture hatred. Reconciliation requires truth and participation from both people. Trust is a judgment about demonstrated reliability and may return gradually, differently, or not at all. Safety boundaries can coexist with forgiveness. Consequences can coexist with mercy. A husband who quotes forgiveness to avoid disclosure, treatment, restitution, or separation for safety is not defending grace; he is using spiritual language to resist accountability.`,
        `The wife who has been harmed is not assigned a timetable in this module. She does not owe immediate conversation, physical affection, public unity, or protection of her husband’s reputation. The husband’s assignment is his own confession or repair attempt. If he fears consequences, he should seek wise counsel before speaking; but not in order to manipulate the response or hide danger. In cases involving crime, abuse, infidelity, addiction, serious deception, or financial exploitation, qualified individual guidance may be essential, and joint conversation may not be the safest first step.`,
        `Small injuries also deserve honest repair. Interrupting, dismissive humor, chronic lateness, broken household promises, or using the phone during vulnerable conversation can wear down trust. Do not reserve repentance for dramatic failure. Prompt repair prevents minor harm from becoming a culture. At the same time, avoid compulsive apology that asks your wife to manage your shame. One clear confession plus changed conduct is more loving than repeated emotional collapse that makes the harmed person comfort the one who caused harm.`,
        `When you are the hurt spouse, truthful boundaries still matter. You may name an injury without contempt, seek clarification, and decide what you need before closeness can resume. This module does not require pretending the other person is safe or repentant. Christian hope is not denial. It can grieve, lament, pursue justice, and wait. If both spouses have harmed each other, each should own his or her conduct without turning confession into a trade: “I will admit mine when you admit yours.” Responsibility is not diminished because another responsibility also exists.`,
        `Accountability should fit the harm. A trusted pastor, counselor, recovery group, financial professional, physician, or legal authority may each have a proper role, but no single helper is qualified for everything. Choose someone who will not collude with secrecy or rush your wife’s response. Do not recruit friends to persuade her that you have changed. If your action creates ongoing risk, accept safeguards that reduce your freedom for a time. Repentance asks, “What protects truth and prevents repetition?” rather than “What is the smallest gesture that will make this consequence end?” Track the commitments you make and report accurately to the proper helper. A vague claim that you are “working on it” cannot replace dates, actions, and honest disclosure. Let truth stay concrete.`,
        `This week, choose one specific wrong you can safely address. Prepare a short confession: what you did, why it was wrong, the impact you understand, and one repair you will make. Ask whether it is a workable time, speak without demanding closure, and then listen. If direct contact would be unsafe or professionally unwise, take the first accountable step with a qualified helper instead. The finish line is a concrete repair attempt and follow-through, not a particular emotional response from your wife.`
      ],
      scripture: [
        { reference: 'Psalm 51:1–12', note: 'David names sin before God without bargaining. The psalm models contrition; it does not remove temporal consequences or entitle the offender to restored trust.' },
        { reference: 'Luke 19:1–10', note: 'Zacchaeus’s repentance includes material restitution. Grace produces accountable action rather than vague regret.' },
        { reference: 'Colossians 3:12–14', note: 'Compassion, patience, and forgiveness belong to Christian character. They must not be severed from truth, justice, or safety.' }
      ],
      fairInsight: `The research is right to distinguish the decision to forgive from the longer work of rebuilding relationship, and to emphasize apology and release of resentment. Naming hurt rather than burying it can interrupt cycles of avoidance and retaliation.`,
      caution: `Forgiveness teaching is easily weaponized. It must not demand silence, erase consequences, collapse trust into mercy, or pressure an endangered spouse to reconcile. Serious betrayal, abuse, addiction, trauma, and criminal conduct require specialized accountability and care beyond a general marriage exercise.`,
      selfCheck: ['Do my apologies name my action, or mainly explain my intentions?', 'What consequence or restitution have I been trying to avoid?', 'Have I confused being forgiven with being trusted?', 'Do I pressure my wife to comfort me when I should be listening to harm?'],
      fieldAction: { title: 'Make one specific confession or repair attempt', steps: ['Choose a specific behavior rather than a global flaw.', 'Name the wrong and its impact without “but.”', 'Offer one concrete repair or accountability step.', 'Allow time and boundaries without demanding forgiveness or closure.'], finishLine: 'You made a safe, specific repair attempt and completed or scheduled the concrete action you offered, without requiring a particular response.' },
      conversation: ['Is there a manageable hurt I need to hear without defending?', 'What impact of my action have I not understood?', 'What repair would be meaningful, if any?', 'What boundary or time do you need me to respect now?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module04FieldManual
    },
    {
      id: 'm05', number: 5, slug: 'module-05.html', title: 'Understand the Family You Brought In',
      question: 'Which inherited assumptions shape my reactions as a husband?',
      missionBrief: [
        `Every husband enters marriage with a working model of family, even if he has never described it. Childhood taught him what conflict sounds like, who handles money, whether affection is spoken, how privacy works, what men are allowed to feel, and what happens when someone fails. Some lessons were explicit; many were absorbed through repetition. Family of origin is influence, not destiny. The point of examining it is neither to blame parents for every choice nor to romanticize endurance. It is to bring inherited assumptions into the light so they can be tested rather than obeyed automatically.`,
        `Start with observation. In your home growing up, who made decisions and how? Were apologies common, rare, or demanded only from children? Did adults discuss money, sex, grief, faith, and anger openly, indirectly, or not at all? What did loyalty require? Which differences were welcomed, mocked, or punished? Avoid turning the exercise into a trial of relatives. Describe patterns and effects. “We avoided disagreement until someone exploded” is more useful than assigning a permanent diagnosis to every family member.`,
        `Then notice current triggers. A spouse’s request to discuss spending may feel like ordinary planning to her and like an accusation of incompetence to you. A need for alone time may feel like regulation to one person and abandonment to another. These reactions often make sense inside an earlier story, but making sense is not the same as being right for the present marriage. Ask, “What old rule does this moment seem to activate?” That question creates a small distance between sensation and action; the space in which a different response becomes possible.`,
        `Honor what was good. Perhaps your family practiced hospitality, worked faithfully, kept promises, prayed together, served neighbors, or stayed connected across generations. Retaining a pattern intentionally is different from repeating it unconsciously. Name why it serves your marriage now and how your wife experiences it. Even virtues can become distorted: loyalty can become secrecy, thrift can become control, toughness can become emotional absence, and closeness can become intrusion. Mature inheritance receives gifts with gratitude and still tests how they are used.`,
        `Replace what harms. Choose one specific pattern, not your entire family system. If men in your family withdrew when ashamed, your replacement may be: “I will say I need twenty minutes and return at a stated time.” If money was controlled through secrecy, your replacement may be a shared view of accounts and agreed personal spending. If affection was mocked, your replacement may be one sincere expression of appreciation each day. A replacement needs a cue and an observable behavior; good intentions disappear when the old trigger arrives.`,
        `Your wife also has a family story, but this module does not authorize you to interpret it for her. Do not weaponize background: “You are acting just like your mother” rarely creates understanding. Invite her view if she wants to share and believe that she is the primary interpreter of her experience. Couples from different cultures, classes, races, regions, church traditions, or family structures may carry practices that are unfamiliar rather than unhealthy. Curiosity asks what a practice means before judging it by one household’s normal.`,
        `Some histories involve trauma, addiction, neglect, abuse, forced migration, racism, poverty, bereavement, or estrangement. A simple family-tree conversation may stir intense memories or increase danger. Do not demand disclosure, contact with relatives, or reconciliation. Do not make your wife prove trauma to earn a boundary. Qualified trauma-informed care can help a person understand reactions without treating him as defective. Past harm may explain present protection, but it never excuses a husband’s current coercion or violence. He remains responsible for seeking help and preventing further harm.`,
        `Build compassion without surrendering discernment. Parents and caregivers were shaped by their own histories, resources, sins, and wounds. Understanding that context may reduce contempt, but it does not rename harm as good or require renewed access. Likewise, rejecting an inherited pattern does not require rejecting every person connected to it. Hold gratitude, grief, anger, and mercy without forcing one emotion to cancel another. Your present responsibility is not to produce a tidy family story. It is to choose conduct that tells the truth and protects the household entrusted to you. Revisit the replacement after several weeks; if it does not survive the real trigger, make the cue simpler and ask for appropriate support.`,
        `This week, identify one inherited pattern to retain and one to replace. Write each as behavior, not a label. Tell your wife only your own findings and ask whether she recognizes their effect; she may decline. Practice the replacement once when the cue appears, or rehearse it calmly if the cue does not arise. The finish line is not a complete explanation of your family. It is one conscious choice: gratitude for a gift, honesty about a cost, and a concrete new response that better serves the covenant you are building now.`
      ],
      scripture: [
        { reference: 'Genesis 2:24', note: 'Marriage forms a new primary household allegiance. “Leaving” does not require contempt for parents, nor does honoring parents require allowing harmful intrusion.' },
        { reference: 'Ezekiel 18:19–23', note: 'The chapter rejects fatalism about inherited guilt and stresses personal responsibility, while not denying that generations affect one another.' },
        { reference: '2 Corinthians 5:17', note: 'New creation in Christ grounds hope for changed patterns; growth still involves truthful practice, repentance, and support.' }
      ],
      fairInsight: `The source research usefully invites couples to map family-of-origin patterns and understand how early experience shapes present expectations. This can replace moral accusation with curiosity and help a couple consciously choose what to carry forward.`,
      caution: `Family narratives can become simplistic blame, amateur diagnosis, or cultural superiority. Insight does not excuse current harm, and “honor your parents” does not require contact or unsafe access. Trauma and abuse histories should not be forced into a couple exercise or handled without appropriate care.`,
      selfCheck: ['Which ordinary marital moment produces a reaction in me that seems larger than the event?', 'What rule about men, emotion, money, conflict, or loyalty did my childhood teach?', 'Which inherited strength does my wife actually experience as a gift?', 'What family comparison have I used unfairly against her?'],
      fieldAction: { title: 'Retain one pattern and replace one pattern', steps: ['Describe one inherited pattern that serves your marriage.', 'Describe one pattern that no longer serves it.', 'Choose a cue and a specific replacement response.', 'Practice or rehearse the replacement once.'], finishLine: 'You named one pattern to retain, one to replace, and carried out the replacement behavior once without diagnosing or assigning homework to your wife.' },
      conversation: ['Would you be willing to tell me how one pattern from my family affects our home?', 'Which strength from my background do you value?', 'When my old pattern appears, what observable response would feel different?', 'Is there a family topic or boundary you do not want this exercise to cross?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module05FieldManual
    },
    {
      id: 'm06', number: 6, slug: 'module-06.html', title: 'Guard Friendship and Intimacy',
      question: 'What deliberate attention does our friendship and intimacy need?',
      missionBrief: [
        `Marital intimacy is larger than sex and includes friendship, safety, affection, delight, knowledge, privacy, and embodied closeness. Sexual intimacy matters, but it cannot be isolated from the rest of married life. Exhaustion, resentment, caregiving, grief, pain, medication, disability, trauma, work pressure, and changing seasons all affect desire and connection. A husband serves intimacy by becoming attentive to the whole environment rather than treating his wife’s body as the location of a problem he wants solved. Connection grows where both people can tell the truth without pressure.`,
        `Friendship requires unclaimed attention. Screens, work, and household demands can consume every open space, leaving spouses to exchange logistics while sharing a room. A no-screen connection block creates a modest counter-practice. Its purpose is not to manufacture romance or guarantee sex. It is to make room for presence. Depending on the marriage, the block could be a walk, coffee, a board game, shared music, a porch conversation, prayer, or quiet affection. The form should fit both spouses’ energy, access needs, culture, and current trust.`,
        `Consent is non-negotiable within marriage. Either spouse may decline any sexual or affectionate activity at any time. Consent must be voluntary, specific, ongoing, and reversible; disappointment does not create entitlement. Freely chosen openness when spontaneous desire is absent can be healthy for some people, but reluctance must never be overridden, spiritualized, or punished. A warm “no” from one spouse and a respectful response from the other can strengthen trust because it proves that closeness is not a hidden contract. No touch is owed as an alternative.`,
        `Many couples experience different levels or patterns of desire. Do not label the higher-desire spouse needy or the lower-desire spouse broken. Do not assume the husband always wants more. Treat the difference as shared information. Ask about pressure, rest, pain, medication, privacy, unresolved hurt, body image, caregiving, and what kinds of contact feel safe. Medical symptoms deserve medical evaluation; trauma deserves trauma-informed care. Candlelight and technique cannot compensate for fear, untreated pain, chronic exhaustion, or ongoing betrayal.`,
        `Affection becomes safer when it carries no secret invoice. Offer kind words, practical partnership, and nonsexual touch because they are goods in themselves, not deposits toward access. Share household and caregiving responsibilities as justice and love, not seduction strategy. Never criticize or compare your wife’s body. Protect her privacy. If every touch has become a request, ask what kinds of connection she would welcome and practice accepting limits without sulking, argument, Scripture pressure, or withdrawal of ordinary kindness.`,
        `Guarding intimacy also means guarding fidelity. Notice when admiration, secrecy, fantasy, messaging, pornography, or emotional disclosure outside the marriage is drawing energy away from covenant truthfulness. Boundaries should be clear enough to guide conduct without becoming mutual surveillance. If attraction to another person is growing, seek wise, confidential help and increase honest accountability. Disclosure to a spouse may require pastoral or clinical guidance when blunt detail would traumatize or manipulate. Active affairs, compulsive sexual behavior, and serious deception need structured intervention before sexual reconnection is treated as a solution.`,
        `Friendship includes play and particular knowledge. Remember what makes your wife laugh, what drains her, what she is learning, and what she hopes for beyond household function. Ask questions without turning the evening into an interview. Let delight be small: a familiar snack, an unhurried walk, a song, a shared memory. Long marriages pass through seasons when elaborate dates are impossible. Deliberate attention can still say, “I see you as a person, not merely a role.” The measure is not expense or novelty but whether the attention is welcome and genuinely shared.`,
        `Speak about intimacy away from the bedroom and outside the immediate sting of rejection. Ask one question at a time and make opting out ordinary. Protect private answers; they are not material for jokes, sermons, friends, or future arguments. If conversation becomes painful, stop and seek an appropriate next step rather than extracting a complete explanation. Prayer can invite humility and care, but it must not become pressure to disclose, forgive, touch, or continue. The husband’s first evidence of love is often whether his wife’s boundary remains safe after she states it. Keep ordinary warmth intact afterward; sulking, coldness, or withdrawal can punish a boundary without ever speaking a threat. Patience protects future honesty and keeps affection from becoming leverage. Welcome boundaries as information that helps genuine closeness remain possible.`,
        `This week, invite one no-screen connection block of at least thirty minutes. Offer two realistic options and make refusal safe. Clarify that the block carries no expectation of sex or disclosure. Put devices away, protect the time, and follow the activity both of you choose. Afterward, ask only whether the experience felt connecting and what should change next time. The finish line is shared, pressure-free attention appropriate to the marriage’s current safety and trust; not a romantic performance and not a particular physical outcome.`
      ],
      scripture: [
        { reference: '1 Corinthians 7:3–5', note: 'Paul emphasizes mutuality rather than one-sided entitlement. Read alongside the whole biblical witness against force, harm, and self-seeking love; the passage must never be used to coerce sex.' },
        { reference: 'Song of Songs 2:7; 8:6–7', note: 'The poetry honors desire’s power and proper timing. Love is not awakened or managed by pressure.' },
        { reference: '1 Corinthians 13:4–7', note: 'Patient, non-self-seeking love provides a moral boundary for affection and sexuality; it does not rejoice in domination or deception.' }
      ],
      fairInsight: `The research rightly connects sexual intimacy with emotional connection, ordinary kindness, conversation, protected time, and non-demand affection. It also normalizes changing seasons and encourages couples to discuss a topic often left to silence.`,
      caution: `Gender stereotypes and “respond even when you do not feel like it” language can become pressure. Consent is always voluntary and reversible. Trauma, sexual pain, medical issues, coercion, addiction, affairs, and major betrayal require specialized care; joint intimacy exercises may be unsafe or premature.`,
      selfCheck: ['Does my affection carry an unspoken expectation of sex or reassurance?', 'How do I respond in words, face, and behavior when my wife says no or not now?', 'What structural pressure; workload, sleep, privacy, unresolved hurt; am I able to address?', 'Where do secrecy or outside attention threaten faithful friendship?'],
      fieldAction: { title: 'Complete one pressure-free no-screen connection block', steps: ['Invite rather than announce, offering realistic choices.', 'Agree on at least thirty minutes and an activity.', 'State clearly that there is no expectation of sex or forced disclosure.', 'Put devices away and review gently afterward.'], finishLine: 'You shared at least thirty minutes of mutually chosen, no-screen connection while respecting every physical and conversational boundary.' },
      conversation: ['What kind of connection would feel welcome this week?', 'What makes affection feel safe and free of hidden expectations?', 'What pressure is affecting your capacity for friendship or intimacy?', 'How can I respond better when your answer is no or not yet?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module06FieldManual
    },
    {
      id: 'm07', number: 7, slug: 'module-07.html', title: 'Put Love into Action',
      question: 'Does my daily conduct communicate love in a way she can recognize?',
      missionBrief: [
        `Love becomes credible through conduct. A husband may feel deep affection and still communicate neglect through inattention, unreliable promises, harsh speech, or leaving the mental load to his wife. Good intentions matter, but marriage is lived in observable moments. This module asks you to choose one small act that your wife can actually recognize as care and repeat it for seven days. The aim is not to earn a reward, prove you are the better spouse, or reduce love to a formula. It is to train attention and faithfulness until care becomes easier to see.`,
        `Popular “love language” categories can be useful prompts: words, time, gifts, service, and touch name different ways people may notice care. They are not diagnoses, fixed personalities, scientific scores, or contracts. A person may value different expressions in different seasons. A tired parent may need practical service more than a date; someone recovering from pressure may not welcome touch. Ask rather than classify. “What action would lighten your week?” is more loving than announcing that you know her category and therefore know what she should appreciate.`,
        `Choose an action that is specific and sustainable. “Be more loving” cannot be observed. “Prepare tomorrow’s lunches before bed for seven days” can. “Say something nice” is vague. “Offer one truthful, specific appreciation each morning without adding a request” is clear. The action should fit a real need and remain within your responsibility. Do not choose something that creates more work for your wife, spends shared money without agreement, violates a boundary, or performs intimacy she has not welcomed.`,
        `Repeat without keeping score. The practice is not seven deposits that entitle you to affection, sex, praise, or equivalent service. If resentment rises because she did not notice, examine the hidden contract. You may tell her you are trying to build a faithful habit, but do not require daily evaluation. Love can be seen and still not produce the response you hoped for, especially when trust has been damaged. Continue the agreed action because it is good, while remaining open to correction if it is not actually helpful.`,
        `Words of appreciation should be truthful and particular. Notice courage, labor, wisdom, creativity, perseverance, humor, or kindness; not only appearance and not only what benefits you. Time should be attentive, not merely occupying the same room. Gifts should respect the budget and the recipient rather than display the giver. Service should share responsibility without treating ordinary adult work as a favor. Touch must always be welcome and never used to test or overcome a boundary. Every expression is governed by truth, justice, and consent.`,
        `If you miss a day, repair the rhythm without drama. Do not restart a public streak, demand reassurance, or abandon the practice because it is no longer perfect. Name the miss if it affected her, complete any neglected responsibility, and continue. A seven-day experiment is meant to reveal friction: poor planning, forgotten cues, unrealistic scope, or a mismatch between your chosen action and her actual need. Use the information. Faithfulness grows through honest adjustment, not image management.`,
        `At the end of seven days, review privately before inviting feedback. Did the action remain generous or become transactional? Was it useful, intrusive, or neutral? What cue helped you remember? What did you learn about the invisible work of the household? Then ask your wife one optional question: “Was this helpful, and should I continue, change, or stop?” Receive the answer without lobbying. A mature husband would rather abandon his preferred gesture than insist that his wife validate it.`,
        `Let service include invisible responsibility. Notice supplies before they run out, appointments before reminders arrive, maintenance before crisis, and family commitments before your wife must delegate them. Owning work means planning and completing it, not asking her to supervise every step. Yet initiative still needs coordination: reorganizing a shared system without consent can create burden rather than relief. Ask what ownership would help, agree on the standard, and then carry the mental as well as physical part. Competent partnership is one way daily love becomes believable. When circumstances change, renegotiate rather than silently dropping the work or resenting the earlier agreement. Quiet faithfulness over time matters more than a dramatic week that cannot be sustained. Build a pace your household can trust. Let dependable care become ordinary, quiet evidence of mature love.`,
        `Course completion is not marriage completion. Carry forward a maintenance rhythm: the weekly check-in, listen-back, pause-and-return, prompt repair, conscious replacement of inherited patterns, protected friendship, and observable care. Choose one practice to continue for the next month. Progress stored here is only seven browser flags; it is not a spiritual score or evidence that your marriage is safe. The real fruit belongs in growing truth, tenderness, responsibility, and willingness to seek help. Finish by taking action, thanking God for grace, and returning tomorrow to ordinary faithfulness.`
      ],
      scripture: [
        { reference: '1 John 3:16–18', note: 'Christian love moves beyond words into truthful action and material care. Action does not make manipulation holy; it must remain rooted in truth.' },
        { reference: 'John 13:1–17', note: 'Jesus joins authority with humble service. His example confronts entitlement rather than assigning a wife to manage her husband’s growth.' },
        { reference: 'Galatians 5:13–14, 22–23', note: 'Service through love and the Spirit’s fruit include patience, kindness, faithfulness, gentleness, and self-control.' }
      ],
      fairInsight: `The source research offers a memorable vocabulary for noticing that care sent in one form may not be recognized in another. Its practical value lies in curiosity, concrete action, and adaptation rather than in treating categories as fixed science.`,
      caution: `Love-language labels can stereotype, excuse neglect, or become bargaining chips: “I did your language, so you owe mine.” They must not override consent, budget, justice, or changing needs. Acts of service do not cancel abuse, deception, addiction, or the need for accountability.`,
      selfCheck: ['Which acts of care do I prefer to give because they cost me least?', 'Have I asked what would actually help, or assigned my wife a category?', 'Where does my service carry a hidden expectation of praise, sex, or repayment?', 'Which one course practice should become a monthly rhythm?'],
      fieldAction: { title: 'Repeat one recognizable act of love for seven days', steps: ['Ask what one observable action would genuinely help.', 'Define it small enough to repeat for seven days.', 'Complete it without asking for repayment or daily praise.', 'After day seven, invite a continue/change/stop answer.'], finishLine: 'You completed the chosen action on seven days, repaired any miss honestly, and received optional feedback without arguing for your preferred gesture.' },
      conversation: ['What one small action from me would make this week lighter or warmer?', 'Is there a form of care I offer that does not currently feel helpful?', 'Should I continue, change, or stop this seven-day practice?', 'Which course rhythm would you welcome for the next month?'],
      support: sharedSupport,
      resources: commonResources,
      fieldManual: module07FieldManual
    }
  ]
};

module.exports = { course };
